// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden"
	raiden_controllers "github.com/sev-2/raiden/pkg/controllers"
	"github.com/valyala/fasthttp"
	"ipmedpointsistem/internal/controllers"
	"ipmedpointsistem/internal/models"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		raiden.NewRouteFromController(&raiden_controllers.StateReadyController{}, []string{fasthttp.MethodPost}),
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/doctor",
			Methods:    []string{fasthttp.MethodGet, fasthttp.MethodPost},
			Controller: &controllers.DoctorController{},
			Model:      models.Doctors{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/doctor-schedule",
			Methods:    []string{fasthttp.MethodGet, fasthttp.MethodPost},
			Controller: &controllers.ScheduleController{},
			Model:      models.DoctorSchedule{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/doctor-schedule/{id}",
			Methods:    []string{fasthttp.MethodPut},
			Controller: &controllers.UpdateScheduleController{},
			Model:      models.DoctorSchedule{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/doctor-schedule/{id}",
			Methods:    []string{fasthttp.MethodDelete},
			Controller: &controllers.DeleteScheduleController{},
			Model:      models.DoctorSchedule{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/doctor/{id}",
			Methods:    []string{fasthttp.MethodDelete},
			Controller: &controllers.DeleteDoctorController{},
			Model:      models.Doctors{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWorldController{},
		},
	})
}
